version: 0.2
phases:
  install: 
    runtime-versions:
      python: 3.7.12
    commands:
      - echo Entered the INSTALLATION phase
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Entered the PRE BUILD phase
  build:
    commands:
      - echo Entered the BUILD phase
    finally:
      - echo This is the finally block execution!
  post_build:
    commands:
      - echo Entered the POST BUILD phase

      