AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ApplicationName:
    Type: String
    Description: Enter the Application name
  KeyName: 
    Type: AWS::EC2::KeyPair::KeyName
  ApplicationRevisionBucket:
    Type: String
    Description: The name of the Amazon S3 bucket where the application revision is stored

Resources:
  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Description: Role used for CodeDeploy to call AWS services 
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - codedeploy.amazonaws.com      #this is for deployment on EC2, need to change this value if the deployment is on ECS / lambda
  
  InstanceRole:
    Type: AWS::IAM::Role
    Description: Role used for EC2 to access S3 artifacts bucket
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  
  InstancePolicy: 
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CodeDeployInstancePolicy
      Roles:
        - !Ref InstanceRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:PutObject
              - s3:Get*
              - s3:List*
            Resource: '*'
              #- !Sub "arn:aws:s3:::codepipeline-${AWS::Region}-*/*"
              #- !Sub "arn:aws:s3:::${DeploymentArtifactBucket}/*"
      Roles:
        - !Ref InstanceRole
  
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: ec2-instance-profile
      #Path: /
      Roles: 
       - !Ref InstanceRole

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: SG to allow SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
      Tags:
        - Key: Name
          Value: InstanceSecurityGroup

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: ami-0cff7528ff583bf9a
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds: 
        - !Ref InstanceSecurityGroup
      Tags: 
        - 
          Key: Type
          Value: CodeDeloyEC2
        -
          Key: Name
          Value: EC2byCodeDeploy
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash
            sudo yum update -y
            sudo yum install wget
            sudo amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
            sudo yum install -y httpd 
            sudo systemctl start httpd
            sudo systemctl enable httpd
            sudo systemctl is-enabled httpd
            cd /home/ec2-user
            wget https://aws-codedeploy-us-east-2.s3.amazonaws.com/latest/install
            chmod +x ./install
            sudo ./install auto

  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties: 
      ApplicationName: !Ref ApplicationName
      ComputePlatform: Server
      Tags: 
        - 
          Key: Name
          Value: !Ref ApplicationName
  
  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    DependsOn: CodeDeployApplication
    Properties: 
      ApplicationName: !Ref CodeDeployApplication
      Deployment:
        Description: Description of Deployment for Application to which location
        IgnoreApplicationStopFailures: true
        Revision:
          RevisionType: S3
          S3Location:
            Bucket: !Ref ApplicationRevisionBucket
            Key: build-output.zip
            BundleType: Zip
      DeploymentConfigName: CodeDeployDefault.AllAtOnce
      DeploymentStyle: 
        DeploymentOption: WITHOUT_TRAFFIC_CONTROL
        DeploymentType: IN_PLACE
      Ec2TagFilters: 
        - 
          Key: Type
          Type: KEY_AND_VALUE
          Value: CodeDeloyEC2
      ServiceRoleArn: !GetAtt CodeDeployServiceRole.Arn
      Tags: 
        - 
          Key: Name
          Value: !Ref CodeDeployApplication
      
Outputs:
  ServiceRoleArn:
    Description: Arn of IAM service role
    Value: !GetAtt CodeDeployServiceRole.Arn
  ServiceRoleId: 
    Description: Role ID of IAM service role
    Value: !GetAtt CodeDeployServiceRole.RoleId
  InstanceRoleArn: 
    Description: Arn of IAM instance role
    Value: !GetAtt InstanceRole.Arn
  InstanceRoleId: 
    Description: Role ID of IAM instance role
    Value: !GetAtt InstanceRole.RoleId
  InstanceProfileArn: 
    Description: Arn of Instance Profile
    Value: !GetAtt InstanceProfile.Arn
  EC2SecurityGroupGroupID: 
    Description: Security group ID for EC2 instances
    Value: !GetAtt InstanceSecurityGroup.GroupId
  EC2AZ:
    Description: AZ of the EC2 instance
    Value: !GetAtt EC2Instance.AvailabilityZone
  EC2PublicDNS: 
    Description: Public DNS name of EC2 instance
    Value: !GetAtt EC2Instance.PublicDnsName
  EC2PublicIP:
    Description: Public IP of EC2 instance
    Value: !GetAtt EC2Instance.PublicIp


