AWSTemplateFormatVersion: 2010-09-09

Description: 
  Adding CW event for CodePipeline- https://docs.aws.amazon.com/codepipeline/latest/userguide/update-change-detection.html#update-change-detection-cfn-codecommit

Parameters:
  ArtifactBucket:
    Type: String
    Description: S3 bucket where build artifacts are stored
  ProjectName:
    Type: String
    Description: The name of the project being built.  This name will be used on a number of resources.
  ArtifactBucketObjectKey:
    Type: String
    Description: Mention the complete path of the projet file
  CodeBuildProjectArn:
    Type: String
    Description: Arn of the CodeBuild Project
  BranchName: 
    Type: String
  RepositoryName: 
    Type: String
  CodeDeployApplication: 
    Type: String
  CodeDeployGroup: 
    Type: String

Resources:

  AmazonCloudWatchEventRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: cwe-pipeline-execution
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action: codepipeline:StartPipelineExecution
                Resource: !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref AppPipeline ] ]
  
  AmazonCloudWatchEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - 'CodeCommit Repository State Change'
        resources:
          - !Join [ '', [ 'arn:aws:codecommit:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref RepositoryName ] ]
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - main
      Targets:
        -
          Arn: 
            !Join [ '', [ 'arn:aws:codepipeline:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':', !Ref AppPipeline ] ]
          RoleArn: !GetAtt AmazonCloudWatchEventRole.Arn
          Id: codepipeline-AppPipeline

  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - codepipeline.amazonaws.com
      Tags:
        - Key: Name
          Value: CodePipelineServiceRole
  
  CodePipelineServicePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CodePipelineServicePolicy
      Roles:
        - !Ref CodePipelineServiceRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - iam:PassRole
            Resource: "*"
            Effect: Allow
            Condition:
              StringEqualsIfExists:
                iam:PassedToService:
                  - cloudformation.amazonaws.com
                  - elasticbeanstalk.amazonaws.com
                  - ec2.amazonaws.com
                  - ecs-tasks.amazonaws.com
          - Action:
              - codecommit:CancelUploadArchive
              - codecommit:GetBranch
              - codecommit:GetCommit
              - codecommit:GetRepository
              - codecommit:GetUploadArchiveStatus
              - codecommit:UploadArchive
            Resource: "*"
            Effect: Allow
          - Action:
              - codedeploy:CreateDeployment
              - codedeploy:GetApplication
              - codedeploy:GetApplicationRevision
              - codedeploy:GetDeployment
              - codedeploy:GetDeploymentConfig
              - codedeploy:RegisterApplicationRevision
            Resource: "*"
            Effect: Allow
          - Action:
              - codestar-connections:UseConnection
            Resource: "*"
            Effect: Allow
          - Action:
              - elasticbeanstalk:*
              - ec2:*
              - elasticloadbalancing:*
              - autoscaling:*
              - cloudwatch:*
              - s3:*
              - sns:*
              - cloudformation:*
              - rds:*
              - sqs:*
              - ecs:*
            Resource: "*"
            Effect: Allow
          - Action:
              - lambda:InvokeFunction
              - lambda:ListFunctions
            Resource: "*"
            Effect: Allow
          - Action:
              - opsworks:CreateDeployment
              - opsworks:DescribeApps
              - opsworks:DescribeCommands
              - opsworks:DescribeDeployments
              - opsworks:DescribeInstances
              - opsworks:DescribeStacks
              - opsworks:UpdateApp
              - opsworks:UpdateStack
            Resource: "*"
            Effect: Allow
          - Action:
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStacks
              - cloudformation:UpdateStack
              - cloudformation:CreateChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:SetStackPolicy
              - cloudformation:ValidateTemplate
            Resource: "*"
            Effect: Allow
          - Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:BatchGetBuildBatches
              - codebuild:StartBuildBatch
            Resource: "*"
            Effect: Allow
          - Effect: Allow
            Action:
              - devicefarm:ListProjects
              - devicefarm:ListDevicePools
              - devicefarm:GetRun
              - devicefarm:GetUpload
              - devicefarm:CreateUpload
              - devicefarm:ScheduleRun
            Resource: "*"
          - Effect: Allow
            Action:
              - servicecatalog:ListProvisioningArtifacts
              - servicecatalog:CreateProvisioningArtifact
              - servicecatalog:DescribeProvisioningArtifact
              - servicecatalog:DeleteProvisioningArtifact
              - servicecatalog:UpdateProduct
            Resource: "*"
          - Effect: Allow
            Action:
              - cloudformation:ValidateTemplate
            Resource: "*"
          - Effect: Allow
            Action:
              - ecr:DescribeImages
            Resource: "*"
          - Effect: Allow
            Action:
              - states:DescribeExecution
              - states:DescribeStateMachine
              - states:StartExecution
            Resource: "*"
          - Effect: Allow
            Action:
              - appconfig:StartDeployment
              - appconfig:StopDeployment
              - appconfig:GetDeployment
            Resource: "*"

  AppPipeline:          
    Type: AWS::CodePipeline::Pipeline
    DependsOn:
      - CodePipelineServiceRole
      - CodePipelineServicePolicy
      
    Properties: 
      ArtifactStore: 
        Type: S3
        Location: !Ref ArtifactBucket
      
      Name: !Ref ProjectName
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      Stages:  
      - 
        Name: Source 
        Actions: 
          - 
            Name: Source
            ActionTypeId: 
              Category: Source 
              Owner: AWS 
              Version: 1 
              Provider: CodeCommit 
            OutputArtifacts: 
              - 
                Name: SourceArtifact 
            Configuration: 
              BranchName: !Ref BranchName
              RepositoryName: !Ref RepositoryName
              PollForSourceChanges: false
            RunOrder: 1 
      - 
        Name: Build
        Actions:
          - 
            Name: Build
            ActionTypeId:
              Category: Build
              Owner: AWS
              Provider: CodeBuild
              Version: '1'
            RunOrder: 1
            Configuration:
              BatchEnabled: 'false'
              ProjectName: !Ref CodeBuildProjectArn
            OutputArtifacts:
              - 
                Name: BuildArtifact
            InputArtifacts:
              - 
                Name: SourceArtifact
            Namespace: BuildVariables
      
      - 
        Name: ApprovalPostTesting
        Actions:
          - 
            #InputArtifacts: []
            Name: QA
            ActionTypeId:
              Category: Approval
              Owner: AWS
              Version: '1'
              Provider: Manual
            #OutputArtifacts: []
            Configuration:
              #NotificationArn:
                #Fn::Join:
                #- ''
                #- - 'arn:aws:sns:'
                  #- Ref: AWS::Region
                  #- ":"
                  #- Ref: AWS::AccountId
                  #- ":"
                  #- Ref: SNSTopic
              CustomData: Approval or Reject this change after running the Tests
            RunOrder: 1

      - 
        Name: Deploy
        Actions:
          - 
            Name: Deploy
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: '1'
              Provider: CodeDeploy
            Configuration:
              ApplicationName: !Ref CodeDeployApplication
              DeploymentGroupName: !Ref CodeDeployGroup
            InputArtifacts:
              - Name: BuildArtifact
            RunOrder: 1

Outputs:
  CodePipelineServiceRoleArn:
    Description: Arn of CodePipeline service role
    Value: !GetAtt CodePipelineServiceRole.Arn
  CloudWatchEventRuleArn:
    Description: Arn of CloudWatch Event Rule
    Value: !GetAtt AmazonCloudWatchEventRule.Arn
  CloudWatchEventRoleArn:
    Description: Arn of CloudWatch Event Role
    Value: !GetAtt AmazonCloudWatchEventRole.Arn
  PipelineVersion: 
    Description: Version of CodePipeline
    Value: !GetAtt AppPipeline.Version