AWSTemplateFormatVersion: 2010-09-09

Description: 
  This template will create a Build for the application.

Parameters:
  CodeBuildProjectName:
    Type: String
    Description: Only alphanumeric characters, dash, and underscore are supported .
  CodeCommitRepoURL:
    Type: String
    Description: The HTTPS clone URL to the repository 
  ProjectName:
    Type: String
    Description: Name of the project you want to be deployed in CodeCommit

Resources:
  
  # S3 bucket where build artifacts go
  DeploymentArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: Private
      VersioningConfiguration:
        Status: Suspended

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - codebuild.amazonaws.com
                
  CodeBuildServicePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CodeBuildServicePolicy
      Roles:
        - !Ref CodeBuildServiceRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "arn:aws:logs:*:*:*"
          - Effect: Allow
            Action: '*'
              #- s3:GetObject
              #- s3:GetObjectVersion
              #- s3:PutObject
            Resource: '*'
              #- !Sub "arn:aws:s3:::codepipeline-${AWS::Region}-*/*"
              #- !Sub "arn:aws:s3:::${DeploymentArtifactBucket}/*"

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Description: We are setting our Artifacts parameter to be S3 and putting our builds in folder named after BUILD_ID in S3 bucket
    Properties: 
      Artifacts:
        #Type: NO_ARTIFACTS #The build project does not produce any build output
        #Type: CODEPIPELINE #The build project has build output generated through CodePipeline
        Type: S3           #The build project stores build output in Amazon S3
        Location: !Ref DeploymentArtifactBucket          #bucket name
        EncryptionDisabled: True
        Path: NONE
        NamespaceType: BUILD_ID
        Name: build-output.zip
        Packaging: ZIP


      BadgeEnabled: True
      Description: CodeBuild for the project
      Environment: 
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:1.0
        EnvironmentVariables:
          - Name: BUILD_ARTIFACT_BUCKET
            Value: !Ref DeploymentArtifactBucket
      Name: !Ref CodeBuildProjectName
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source: 
        Type: CODECOMMIT
        Location: !Ref CodeCommitRepoURL
      Tags: 
        - 
          Key: Name
          Value: !Ref ProjectName
      TimeoutInMinutes: 10

Outputs:
  BuildArn:
    Description: Arn of the CodeBuild Project
    Value: !GetAtt CodeBuildProject.Arn
  S3Arn:
    Description: Arn of the S3 bucket
    Value: !GetAtt DeploymentArtifactBucket.Arn
  IAMRoleArn:
    Description: Arn of IAM role
    Value: !GetAtt CodeBuildServiceRole.Arn
  IAMRoleId: 
    Description: Role ID of IAM role
    Value: !GetAtt CodeBuildServiceRole.RoleId
  